name = "matercable"
compatibility_date = "2025-05-22"

main = "./.svelte-kit/cloudflare-workers/entry.js"

compatibility_flags = ["nodejs_compat"]  # Optional but useful for Node-like behavior

[build]
command = "npm run build"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" }
]
